// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transport.Infrastructure.Store;

namespace Transport.App.API.Migrations
{
    [DbContext(typeof(TransportContext))]
    [Migration("20211112121711_Transport_V5")]
    partial class Transport_V5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transport.Domain.Models.DbEntities.TransportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfProduction")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<string>("MarkGeoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkLatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelGeoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelLatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Photo")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WinCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transport");
                });

            modelBuilder.Entity("Transport.Domain.Models.DbEntities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalNumber")
                        .IsUnique()
                        .HasFilter("[PersonalNumber] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Transport.Domain.Models.DbEntities.TransportEntity", b =>
                {
                    b.HasOne("Transport.Domain.Models.DbEntities.UserEntity", "User")
                        .WithMany("Transports")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Transport.Domain.Models.DbEntities.UserEntity", b =>
                {
                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
